"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/lib/firebaseClient";
const money = (c) => new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" }).format(c / 100);
export default function AdminFounders() { const [state, setState] = useState({ loading: true, founders: [] }); const [search, setSearch] = useState(""); const [tier, setTier] = useState(""); const [recognition, setRecognition] = useState(""); const [status, setStatus] = useState("");
  useEffect(() => onAuthStateChanged(auth, async (user) => { if (!user) return setState({ loading: false, error: "Sign in with an approved admin account." }); try { const response = await fetch("/api/admin/founders", { headers: { Authorization: `Bearer ${await user.getIdToken()}` } }); if (!response.ok) throw new Error(); setState({ loading: false, ...(await response.json()) }); } catch { setState({ loading: false, error: "Founder records are unavailable or access was denied.", founders: [] }); } }), []);
  const shown = useMemo(() => state.founders.filter((f) => (!search || String(f.founderNumber).includes(search) || f.accountIdentifier.toLowerCase().includes(search.toLowerCase())) && (!tier || (f.earnedTierName || "None") === tier) && (!recognition || f.recognitionMode === recognition) && (!status || f.status === status)), [state.founders, search, tier, recognition, status]);
  if (state.loading) return <main className="founder-admin"><p>Loading Founder records…</p></main>;
  return <main className="founder-admin"><header><p className="founder-kicker">Secure entitlement view</p><h1>Founder management.</h1><Link className="founder-home-link" href="/admin/dashboard">Admin home</Link></header>{state.error ? <div className="founder-notice founder-notice-warning" role="alert">{state.error}</div> : <><section className="founder-admin-summary"><article><span>Founders</span><strong>{state.founders.length}</strong></article><article><span>Eligible campaign total</span><strong>{money(state.founders.reduce((n, f) => n + f.eligibleContributionCents, 0))}</strong></article></section><section className="founder-toolbar" aria-label="Founder filters"><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search number or account" aria-label="Search founders"/><select value={tier} onChange={(e) => setTier(e.target.value)}><option value="">All tiers</option>{[...new Set(state.founders.map((f) => f.earnedTierName || "None"))].map((v) => <option key={v}>{v}</option>)}</select><select value={recognition} onChange={(e) => setRecognition(e.target.value)}><option value="">All recognition</option><option value="anonymous">Anonymous</option><option value="public">Public opt-in</option></select><select value={status} onChange={(e) => setStatus(e.target.value)}><option value="">All statuses</option><option value="active">Active</option><option value="inactive">Inactive</option><option value="disputed_hold">Disputed hold</option></select></section><section className="founder-table">{shown.length ? shown.map((f) => <details key={f.founderNumber}><summary><strong>#{String(f.founderNumber).padStart(4, "0")}</strong><span>{f.accountIdentifier}</span><span>{f.earnedTierName || "No tier"}</span><span>{money(f.eligibleContributionCents)}</span><span className={`founder-status founder-status-${f.status}`}>{f.status.replaceAll("_", " ")}</span></summary><div className="founder-detail"><span>Confirmed <strong>{money(f.confirmedContributionCents)}</strong></span><span>Refunded <strong>{money(f.refundedContributionCents)}</strong></span><span>Disputed <strong>{money(f.disputedContributionCents)}</strong></span><span>Recognition <strong>{f.recognitionMode}</strong></span><span>Created <strong>{f.createdAt ? new Date(f.createdAt).toLocaleDateString("en-CA") : "Unavailable"}</strong></span><span>Updated <strong>{f.updatedAt ? new Date(f.updatedAt).toLocaleDateString("en-CA") : "Unavailable"}</strong></span></div></details>) : <p>No Founder records match these filters.</p>}</section></>}</main>;
}
