"use client";
import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "@/lib/firebaseClient";
const money = (cents) => new Intl.NumberFormat("en-CA", { style: "currency", currency: "CAD" }).format(cents / 100);
export default function FounderProfile() {
  const [state, setState] = useState({ loading: true });
  const load = useCallback(async (user) => { try { const token = await user.getIdToken(); const response = await fetch("/api/founder/profile", { headers: { Authorization: `Bearer ${token}` }, cache: "no-store" }); if (!response.ok) throw new Error(); setState({ loading: false, ...(await response.json()) }); } catch { setState({ loading: false, error: "Your Founder details are unavailable right now." }); } }, []);
  useEffect(() => onAuthStateChanged(auth, (user) => user ? load(user) : setState({ loading: false, signedOut: true })), [load]);
  async function choose(publicRecognitionEnabled) { setState((old) => ({ ...old, saving: true })); try { const token = await auth.currentUser.getIdToken(); const response = await fetch("/api/founder/profile", { method: "PATCH", headers: { Authorization: `Bearer ${token}`, "Content-Type": "application/json" }, body: JSON.stringify({ recognitionMode: publicRecognitionEnabled ? "public" : "anonymous", publicRecognitionEnabled }) }); if (!response.ok) throw new Error(); setState({ loading: false, ...(await response.json()), saved: true }); } catch { setState((old) => ({ ...old, saving: false, error: "The preference could not be saved. Please retry." })); } }
  if (state.loading) return <main className="founder-portal"><p className="founder-kicker">Loading Founder profile…</p></main>;
  if (state.signedOut) return <main className="founder-portal"><h1>Sign in required.</h1><Link className="button button-primary founder-page-action" href="/tattoo-portal">Sign in</Link></main>;
  if (state.error && !state.profile) return <main className="founder-portal"><h1>Founder profile unavailable.</h1><p>{state.error}</p><button className="button button-primary founder-page-action" onClick={() => auth.currentUser && load(auth.currentUser)}>Retry</button></main>;
  if (!state.profile) return <main className="founder-portal"><p className="founder-kicker">Fawcett Founder</p><h1>Your Founder story can start here.</h1><p>No confirmed Founder profile is connected to this account yet.</p><Link href="/founders" className="button button-primary founder-page-action">Explore the campaign</Link></main>;
  const p = state.profile;
  return <main className="founder-portal"><header className="founder-portal-header"><div><p className="founder-kicker">{p.hasPermanentFounderStatus ? "Permanent studio recognition" : "Founder profile"}</p><h1>{p.hasPermanentFounderStatus ? `Founder #${String(p.founderNumber).padStart(4, "0")}` : "Your Founder progress"}</h1></div><Link className="founder-home-link" href="/portal/dashboard">Portal home</Link></header>
    {p.status === "disputed_hold" && <div className="founder-notice founder-notice-warning"><strong>Benefits are currently on hold.</strong><span>A disputed contribution remains recorded while it is reviewed.</span></div>}
    {(p.refundedContributionCents > 0 || p.disputedContributionCents > 0) && <div className="founder-notice"><span>Refunded: {money(p.refundedContributionCents)}</span><span>Disputed: {money(p.disputedContributionCents)}</span></div>}
    <section className="founder-profile-grid"><article className="founder-identity"><p>Entitlement status</p><h2>{p.status.replaceAll("_", " ")}</h2><p>This describes your account entitlement, separately from your earned reward tier.</p></article><article className="founder-metrics"><div><span>Eligible now</span><strong>{money(p.eligibleContributionCents)}</strong></div><div><span>Confirmed lifetime</span><strong>{money(p.confirmedContributionCents)}</strong></div></article></section>
    <section className="founder-panel founder-benefits" aria-labelledby="founder-benefits-title"><div className="founder-benefits-copy"><p className="founder-kicker">Your Founder benefits</p><h2 id="founder-benefits-title">{p.earnedTierName || "No tier earned yet"}</h2>{p.earnedBenefits.length > 0 ? <ul className="founder-benefit-list">{p.earnedBenefits.map((benefit) => <li key={benefit}>{benefit}</li>)}</ul> : <p>Confirmed eligible contributions have not reached the first Founder tier yet.</p>}{p.hasPermanentFounderStatus && <div className="founder-details"><h3>Founder details</h3><dl><div><dt>Founder number</dt><dd>#{String(p.founderNumber).padStart(4, "0")}</dd></div><div><dt>Recognition</dt><dd>{p.recognitionMode === "public" ? "Future public recognition" : "Anonymous"}</dd></div></dl></div>}</div><div className="founder-badge-placeholder" role="img" aria-label={`${p.earnedTierName || "Founder tier"} badge placeholder`}><span>Fawcett</span><strong>{p.earnedTierName || "Tier pending"}</strong><small>Founder badge</small></div></section>
    <section className="founder-panel founder-tier-progress"><p className="founder-kicker">Tier progress</p>{p.nextTier ? <><div className="founder-progress-copy"><h2>Next: {p.nextTier.name}</h2><strong>{money(p.nextTier.remainingCents)} remaining</strong></div><div className="founder-progress" role="progressbar" aria-label={`Progress toward ${p.nextTier.name}`} aria-valuemin="0" aria-valuemax="100" aria-valuenow={p.nextTier.progressPercent}><span style={{ width: `${p.nextTier.progressPercent}%` }} /></div><div className="founder-next-benefits"><h3>Additional benefits at this tier</h3><ul>{p.nextTier.additionalBenefits.map((benefit) => <li key={benefit}>{benefit}</li>)}</ul></div><p className="founder-progress-explanation">Choose another contribution option. Confirmed contributions add to your lifetime total and accumulate toward higher tiers.</p><Link href="/founders#contribution-options" className="button button-primary founder-page-action">View contribution options</Link></> : <><h2>Top tier complete.</h2><p>You have reached every available Founder tier. Confirmed contributions remain part of your lifetime total.</p><Link href="/founders#contribution-options" className="button button-primary founder-page-action">View contribution options</Link></>}</section>
    <section className="founder-panel"><p className="founder-kicker">Recognition preference</p><h2>{p.recognitionMode === "public" ? "Future public recognition" : "Anonymous recognition"}</h2><p>This opt-in records your preference for future recognition. It does not publish your identity, and there is no public Founder Wall in this phase.</p><div className="founder-choice" role="group" aria-label="Recognition preference"><button aria-pressed={p.recognitionMode === "anonymous"} disabled={state.saving} onClick={() => choose(false)}>Remain anonymous</button><button aria-pressed={p.recognitionMode === "public"} disabled={state.saving} onClick={() => choose(true)}>Opt into future recognition</button></div>{state.saved && <p role="status">Preference saved.</p>}{state.error && <p role="alert">{state.error}</p>}</section>
  </main>;
}
